version: '3.7'

services:
    app:
        build: ./
        image: backtest_dyn_el_prices:latest

        command: streamlit run main.py --server.port 8501
        environment:
            - VIRTUAL_HOST=backtest_dyn_el_prices.amelanq.com
            - VIRTUAL_PORT=8501
            - LETSENCRYPT_HOST=backtest_dyn_el_prices.amelanq.com
            - LETSENCRYPT_EMAIL=XXXXXXXXXXXXXXXXXXXXXXX
            - _DUMMY_VALUE=false
        volumes:
            - ./:/usr/src/app
        #ports:
        #    - 8505:8501
        restart: always
        networks:
            - proxy
            - intranet-streamlit

networks:
  proxy:
    external: true
  intranet-streamlit: